title: <p align="center"> Anirudh Saxena </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/sajan-kedia-b06a6821/">LinkedIn</a> |
  <a href="https://github.com/sajankedia">GitHub</a>
  
  <br>   
 Dedicated and motivated data analyst with proven ability to drive
process efficiency and data integrity. Having 3 years of experience in
data analysis and data warehousing solutions.
  <br>
  </p>



theme: jekyll-theme-minimal
